### ISSUE TITLE
Opam packaging

### ISSUE THREAD

**Issue by Lysxia** [xavierleroy/pringo#1]
Would it be possible to publish pringo on opam?

I would like to use it in QuickChick (coq's QuickCheck) for generating random functions and coinductive values.

**Comment by Lysxia** [comment]
I'll use a pure OCaml implementation for now.

**Comment by xavierleroy** [comment]
Sorry for not following up on this.  I'm not too good with OPAM packaging and was hoping someone else could help with this.
