### ISSUE TITLE
mixGamma should fix results with low popcount

### ISSUE THREAD

**Issue by Lysxia** [xavierleroy/pringo#2]
The `mixGamma` function should "fix" its result if the popcount is too low, but in its current version it is doing the opposite.

https://github.com/xavierleroy/pringo/blob/fa170bca58c3d193bca83f88c2e080f0f1fb5902/stubs.c#L77-L78

This is a bug inherited from a typo in the code of the original SplitMix paper. The text gives the correct interpretation:

> Therefore we require that the number of such pairs, as computed by `Long.bitCount(z ^ (z >>> 1))`, exceed `24`; if it does not, then the candidate `z` is replaced by the `XOR` of `z` and `0xaaaaaaaaaaaaaaaaL`

I found that in this blogpost: http://www.pcg-random.org/posts/bugs-in-splitmix.html

**Comment by xavierleroy** [comment]
Thanks a lot for reporting this error.
